[package]
name = "rustracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = "1.0.12"
kdam = "0.3.0"
rand = "0.8.0"
rayon = "1.7.0"
